Repository bounswe/bounswe2025group10, pull requests merged in 2025-05, with the labels that each got.

#120 Front-end admin user interface and necessary tests added
  application/front-end/zero-waste/index.html
  application/front-end/zero-waste/package-lock.json
  application/front-end/zero-waste/package.json
  application/front-end/zero-waste/public/zero-waste-bg.jpeg
  application/front-end/zero-waste/src/Admin/AdminPanel.jsx
  application/front-end/zero-waste/src/Admin/ChallengeCard.jsx
  application/front-end/zero-waste/src/Admin/ChallengePanel.jsx
  application/front-end/zero-waste/src/Admin/CommentCard.jsx
  application/front-end/zero-waste/src/Admin/CommentPanel.jsx
  application/front-end/zero-waste/src/Admin/PostCard.jsx
  application/front-end/zero-waste/src/Admin/UserCard.jsx
  application/front-end/zero-waste/src/Admin/UserPanel.jsx
  application/front-end/zero-waste/src/App.css
  application/front-end/zero-waste/src/App.jsx
  application/front-end/zero-waste/src/App.tsx
  application/front-end/zero-waste/src/Login/Alert.jsx
  application/front-end/zero-waste/src/Login/AuthContent.jsx
  application/front-end/zero-waste/src/Login/LoginPage.jsx
  application/front-end/zero-waste/src/Login/ProtectedUserRoute.jsx
  application/front-end/zero-waste/src/Login/SignupPage.jsx
  application/front-end/zero-waste/src/MainPage/MainPage.css
  application/front-end/zero-waste/src/MainPage/MainPage.jsx
  application/front-end/zero-waste/src/Tests/Admin/AdminPanel.test.jsx
  application/front-end/zero-waste/src/Tests/Admin/ChallengeCard.test.jsx
  application/front-end/zero-waste/src/Tests/Admin/ChallengePanel.test.jsx
  application/front-end/zero-waste/src/Tests/Admin/CommentCard.test.jsx
  application/front-end/zero-waste/src/Tests/Admin/CommentPanel.test.jsx
  application/front-end/zero-waste/src/Tests/Admin/PostCard.test.jsx
  application/front-end/zero-waste/src/Tests/Admin/UserCard.test.jsx
  application/front-end/zero-waste/src/Tests/Admin/UserPanel.test.jsx
  application/front-end/zero-waste/src/Tests/Login/Alert.test.jsx
  application/front-end/zero-waste/src/Tests/Login/AuthContent.test.jsx
  application/front-end/zero-waste/src/Tests/Login/LoginPage.test.jsx
  application/front-end/zero-waste/src/Tests/Login/ProtectedUserRoute.test.jsx
  application/front-end/zero-waste/src/Tests/Login/SignupPage.test.jsx
  application/front-end/zero-waste/src/main.jsx
  application/front-end/zero-waste/src/main.tsx
  application/front-end/zero-waste/src/setupTests.ts
  application/front-end/zero-waste/src/types.d.ts
  application/front-end/zero-waste/tsconfig.app.json
  application/front-end/zero-waste/tsconfig.json
  application/front-end/zero-waste/tsconfig.node.json
  application/front-end/zero-waste/vite.config.js
  application/front-end/zero-waste/vitest.config.ts
Labels: 3-6 hours

#125 PR for accepting new models and name fixes to the backend branch
  application/__init__.py
  application/backend/__init__.py
  application/backend/api/admin.py
  application/backend/api/models.py
  application/backend/api/serializers.py
  application/backend/docker-compose.yml
  application/backend/project/settings.py
Labels: pr:high, 1-3 hours

#126 Merge backend_umut_cors to backend
  application/backend/project/settings.py
  application/backend/requirements.txt
Labels: pr:urgent

#130 Bugfix/operational error 1824
  application/backend/api/login_and_signup/login_views.py
  application/backend/api/migrations/0001_initial.py
  application/backend/api/migrations/0002_alter_user_options_user_date_joined_user_first_name_and_more.py
  application/backend/api/migrations/0003_alter_user_email.py
  application/backend/api/migrations/0004_alter_user_options_alter_user_table.py
  application/backend/api/tests/test_login.py
  application/backend/project/settings.py
Labels: pr:urgent, 1-3 hours

#135 Merging Feature/dashboard api with backend
  application/backend/api/migrations/0002_waste_userwastes.py
  application/backend/api/migrations/0003_create_waste_types.py
  application/backend/api/migrations/0004_create_initial_tips.py
  application/backend/api/migrations/0005_alter_tips_dislike_count_alter_tips_like_count.py
  application/backend/api/models.py
  application/backend/api/tip/tip_serializer.py
  application/backend/api/tip/tip_views.py
  application/backend/api/urls.py
  application/backend/api/waste/waste_serializer.py
  application/backend/api/waste/waste_views.py
Labels: 1-3 hours

#139 Merge Merging Feature/dashboard api with backend for unit tests
  application/backend/api/tests/test_tips.py
  application/backend/api/tests/test_wastes.py
  application/backend/api/waste/waste_serializer.py
Labels: enhancement, pr:high, 1-3 hours

#140 Feature/admin panel
  application/backend/api/admin_panel/__init__.py
  application/backend/api/admin_panel/admin_panel_serializer.py
  application/backend/api/admin_panel/admin_panel_views.py
  application/backend/api/login_and_signup/login_views.py
  application/backend/api/migrations/0002_waste_userwastes.py
  application/backend/api/migrations/0003_create_waste_types.py
  application/backend/api/migrations/0004_create_initial_tips.py
  application/backend/api/migrations/0005_alter_tips_dislike_count_alter_tips_like_count.py
  application/backend/api/migrations/0006_create_initial_admin_user.py
  application/backend/api/models.py
  application/backend/api/tests/test_admin_panel.py
  application/backend/api/tip/tip_serializer.py
  application/backend/api/tip/tip_views.py
  application/backend/api/urls.py
  application/backend/api/waste/waste_serializer.py
  application/backend/api/waste/waste_views.py
Labels: pr:high, 1-3 hours

#146 Merge backend with main
  application/backend/api/tests/test_tips.py
  application/backend/api/tests/test_wastes.py
  application/backend/api/waste/waste_serializer.py
Labels: enhancement, pr:urgent, 1-3 hours

#147 implemented login & signup pages and handled the navigator, ready to merge
  application/mobile/App.tsx
  application/mobile/package-lock.json
  application/mobile/package.json
  application/mobile/src/navigation/AppNavigator.tsx
  application/mobile/src/screens/HomeScreen.tsx
  application/mobile/src/screens/auth/LoginScreen.tsx
  application/mobile/src/screens/auth/SignupScreen.tsx
  application/mobile/src/services/api.ts
  application/mobile/src/utils/storage.ts
  application/mobile/src/utils/theme.ts
  application/package-lock.json
  application/package.json
Labels: enhancement, 1-3 hours

#152 Mobile Login and Signup Improvements
  application/backend/api/login_and_signup/login_serializer.py
  application/backend/api/login_and_signup/login_views.py
  application/backend/project/settings.py
  application/mobile/App.tsx
  application/mobile/src/context/AuthContext.tsx
  application/mobile/src/navigation/AppNavigator.tsx
  application/mobile/src/screens/HomeScreen.tsx
  application/mobile/src/screens/auth/LoginScreen.tsx
  application/mobile/src/screens/auth/SignupScreen.tsx
  application/mobile/src/services/api.ts
Labels: help wanted, pr:high, analyze, 1-3 hours

#155 Implement Challenges API
  application/backend/api/admin_panel/admin_panel_serializer.py
  application/backend/api/migrations/0001_initial.py
  application/backend/api/models.py
  application/backend/api/tests/test_admin_panel.py
  application/backend/challenges/__init__.py
  application/backend/challenges/admin.py
  application/backend/challenges/apps.py
  application/backend/challenges/migrations/0001_initial.py
  application/backend/challenges/migrations/__init__.py
  application/backend/challenges/models.py
  application/backend/challenges/serializers.py
  application/backend/challenges/tests.py
  application/backend/challenges/urls.py
  application/backend/challenges/views.py
  application/backend/project/settings.py
  application/backend/project/urls.py
Labels: enhancement, pr:high

#168 Pulling Backend to Main
  application/backend/api/migrations/0007_report.py
  application/backend/api/report_system/__init__.py
  application/backend/api/report_system/admin_panel_views.py
  application/backend/api/report_system/report_views.py
  application/backend/api/report_system/serializers.py
  application/backend/api/tests/test_report_system.py
  application/backend/api/urls.py
  application/backend/docker-compose.yml
Labels: pr:urgent, 1-3 hours

#136 login and sign up has been fixed
  application/front-end/zero-waste/.gitignore
  application/front-end/zero-waste/package.json
  application/front-end/zero-waste/src/Admin/AdminPanel.jsx
  application/front-end/zero-waste/src/App.jsx
  application/front-end/zero-waste/src/Login/AuthContent.jsx
  application/front-end/zero-waste/src/Login/LoginPage.jsx
  application/front-end/zero-waste/src/Login/ProtectedAdminRoute.jsx
  application/front-end/zero-waste/src/Tests/Admin/AdminPanel.test.jsx
  application/front-end/zero-waste/src/Tests/Login/AuthContent.test.jsx
  application/front-end/zero-waste/src/Tests/Login/LoginPage.test.jsx
  application/front-end/zero-waste/src/Tests/Login/ProtectedAdminRoute.test.jsx
  application/front-end/zero-waste/src/setupTests.js
  application/front-end/zero-waste/src/types.d.ts
  application/front-end/zero-waste/src/vite-env.d.ts
  application/front-end/zero-waste/tsconfig.app.json
  application/front-end/zero-waste/tsconfig.json
  application/front-end/zero-waste/tsconfig.node.json
  application/front-end/zero-waste/vite.config.js
  application/front-end/zero-waste/vitest.config.ts
Labels: 1-3 hours

#172 Feature -front end - challenges, community and tip pages
  application/front-end/zero-waste/index.html
  application/front-end/zero-waste/package-lock.json
  application/front-end/zero-waste/package.json
  application/front-end/zero-waste/public/zero-waste-bg.jpeg
  application/front-end/zero-waste/src/App.css
  application/front-end/zero-waste/src/App.jsx
  application/front-end/zero-waste/src/Login/Alert.jsx
  application/front-end/zero-waste/src/Login/AuthContent.jsx
  application/front-end/zero-waste/src/Login/LoginPage.jsx
  application/front-end/zero-waste/src/Login/ProtectedAdminRoute.jsx
  application/front-end/zero-waste/src/Login/ProtectedUserRoute.jsx
  application/front-end/zero-waste/src/Login/SignupPage.jsx
  application/front-end/zero-waste/src/MainPage/MainPage.css
  application/front-end/zero-waste/src/MainPage/MainPage.jsx
  application/front-end/zero-waste/src/Tests/Login/Alert.test.jsx
  application/front-end/zero-waste/src/Tests/Login/AuthContent.test.jsx
  application/front-end/zero-waste/src/Tests/Login/ProtectedAdminRoute.test.jsx
  application/front-end/zero-waste/src/Tests/Login/ProtectedUserRoute.test.jsx
  application/front-end/zero-waste/src/Tests/components/Community.test.jsx
  application/front-end/zero-waste/src/Tests/components/Post.test.jsx
  application/front-end/zero-waste/src/Tests/components/Tips.test.jsx
  application/front-end/zero-waste/src/Tests/pages/Challenges.test.jsx
  application/front-end/zero-waste/src/Tests/pages/ProfilePage.test.jsx
  application/front-end/zero-waste/src/components/Alert.jsx
  application/front-end/zero-waste/src/components/ChallengeCard.jsx
  application/front-end/zero-waste/src/components/Navbar.css
  application/front-end/zero-waste/src/components/Navbar.jsx
  application/front-end/zero-waste/src/components/Post.jsx
  application/front-end/zero-waste/src/components/SkeletonCard.jsx
  application/front-end/zero-waste/src/index.css
  application/front-end/zero-waste/src/main.jsx
  application/front-end/zero-waste/src/pages/Challenges.jsx
  application/front-end/zero-waste/src/pages/Community.jsx
  application/front-end/zero-waste/src/pages/ProfilePage.jsx
  application/front-end/zero-waste/src/pages/Tips.jsx
  application/front-end/zero-waste/src/providers/ToastProvider.jsx
  application/front-end/zero-waste/src/util/helper.js
  application/front-end/zero-waste/src/util/toast.js
  application/front-end/zero-waste/vite.config.js
Labels: pr:high

#173 Pulling mock data generation command to main
  application/backend/api/management/__init__.py
  application/backend/api/management/commands/__init__.py
  application/backend/api/management/commands/create_mock_data.py
  application/backend/requirements.txt
Labels: pr:urgent, 1-3 hours

#167 Merge Feature/leaderboard api to main
  application/backend/api/login_and_signup/login_views.py
  application/backend/api/migrations/0004_alter_tips_dislike_count_alter_tips_like_count.py
  application/backend/api/migrations/0004_create_initial_tips.py
  application/backend/api/migrations/0005_create_initial_admin_user.py
  application/backend/api/migrations/0006_report.py
  application/backend/api/models.py
  application/backend/api/profile/profile_views.py
  application/backend/api/tests/test_profile.py
  application/backend/api/tests/test_tips.py
  application/backend/api/tests/test_wastes.py
  application/backend/api/urls.py
  application/backend/api/waste/waste_views.py
  application/backend/project/settings.py
  application/backend/project/urls.py
Labels: enhancement, pr:high, 1-3 hours

#180 Fixes has been made , and the authentication is now working properly.
  application/front-end/zero-waste/package-lock.json
  application/front-end/zero-waste/package.json
  application/front-end/zero-waste/src/Login/AuthContent.jsx
  application/front-end/zero-waste/src/Login/LoginPage.jsx
  application/front-end/zero-waste/src/Login/ProtectedAdminRoute.jsx
  application/front-end/zero-waste/src/Tests/Login/AuthContent.test.jsx
Labels: 1-3 hours

#179 Merge Feature/tips api into main
  application/backend/api/migrations/0007_tips_title.py
  application/backend/api/models.py
  application/backend/api/tests/test_tips.py
  application/backend/api/tip/tip_serializer.py
  application/backend/api/tip/tip_views.py
  application/backend/api/urls.py
Labels: enhancement, pr:urgent, 1-3 hours

#193 Implement Automatic Challenge Progress Updates When Logging Waste
  application/backend/api/tests/test_wastes.py
  application/backend/api/waste/waste_views.py
  application/backend/challenges/migrations/0002_alter_challenge_current_progress.py
  application/backend/challenges/models.py
Labels: enhancement, pr:high, 1-3 hours

#194 Added the Post and Comment api and its unit tests
  application/backend/api/comment/__init__.py
  application/backend/api/comment/comment_serializer.py
  application/backend/api/comment/comment_views.py
  application/backend/api/migrations/0008_posts_dislike_count_posts_like_count_postlikes.py
  application/backend/api/migrations/0009_savedposts.py
  application/backend/api/models.py
  application/backend/api/post/__init__.py
  application/backend/api/post/post_serializer.py
  application/backend/api/post/post_views.py
  application/backend/api/tests/test_comments.py
  application/backend/api/tests/test_posts.py
  application/backend/api/urls.py
Labels: enhancement, pr:urgent, 1-3 hours

#195 Feature/profile
  application/backend/api/profile/profile_views.py
  application/backend/api/tests/test_bio.py
  application/backend/api/tests/test_profile.py
  application/backend/api/urls.py
  application/backend/project/settings.py
Labels: enhancement, pr:high, 1-3 hours

#190 merge Feature/climatiq api into main
  application/backend/api/login_and_signup/login_views.py
  application/backend/api/tests/test_tips.py
  application/backend/api/tests/test_wastes.py
  application/backend/api/waste/waste_views.py
  application/backend/requirements.txt
Labels: enhancement, pr:high, 1-3 hours

#198 Extending report creation in create_mock_data command
  application/backend/api/management/commands/create_mock_data.py
Labels: pr:high, 1-3 hours

#202 Merge Bug/leaderboard other fixes to main
  application/backend/api/management/commands/create_mock_data.py
  application/backend/api/migrations/0010_users_total_co2_users_total_points.py
  application/backend/api/models.py
  application/backend/api/tests/test_wastes.py
  application/backend/api/waste/waste_views.py
Labels: pr:urgent, analyze, 1-3 hours

#211 Added title generation to tips
  application/backend/api/management/commands/create_mock_data.py
Labels: pr:high

#217 Merge Feature/modify tips api to connect with frontend into main
  application/backend/api/login_and_signup/login_views.py
  application/backend/api/management/commands/create_mock_data.py
  application/backend/api/migrations/0011_tiplikes.py
  application/backend/api/models.py
  application/backend/api/tests/test_tips.py
  application/backend/api/tip/tip_serializer.py
  application/backend/api/tip/tip_views.py
  application/backend/api/urls.py
Labels: enhancement, pr:urgent, 1-3 hours

#216 profile and post logic has been fixed
  application/front-end/zero-waste/src/Admin/AdminPanel.jsx
  application/front-end/zero-waste/src/Admin/ChallengeCard.jsx
  application/front-end/zero-waste/src/Admin/ChallengePanel.jsx
  application/front-end/zero-waste/src/Admin/UserCard.jsx
  application/front-end/zero-waste/src/Admin/UserPanel.jsx
  application/front-end/zero-waste/src/pages/ProfilePage.jsx
Labels: pr:urgent, 1-3 hours

#207 Merge feature/image-upload-for-posts to main
  application/backend/api/models.py
  application/backend/api/post/post_serializer.py
  application/backend/api/post/post_views.py
  application/backend/api/tests/test_posts.py
Labels: enhancement, pr:urgent, 1-3 hours

#220 Feature/modify posts api to connect with frontend
  application/backend/api/management/commands/create_mock_data.py
  application/backend/api/post/post_serializer.py
  application/backend/api/post/post_views.py
  application/backend/api/tests/test_posts.py
  application/backend/api/tests/test_tips.py
  application/backend/api/tip/tip_views.py
  application/backend/api/urls.py
Labels: enhancement, pr:urgent, 1-3 hours

#226 Update ChallengesScreen: use correct API, authentication, and backend…
  application/mobile/src/screens/ChallengesScreen.tsx
Labels: enhancement, 1-3 hours

#227 Feature/frontend leaderboard
  application/front-end/zero-waste/package-lock.json
  application/front-end/zero-waste/package.json
  application/front-end/zero-waste/src/App.jsx
  application/front-end/zero-waste/src/Leaderboard/Leaderboard.jsx
  application/front-end/zero-waste/src/MainPage/MainPage.jsx
  application/front-end/zero-waste/src/MainPage/WeatherWidget.jsx
  application/front-end/zero-waste/src/Tests/Leaderboard/Leaderboard.test.jsx
  application/front-end/zero-waste/src/setupTests.js
  application/package-lock.json
  application/package.json
Labels: 1-3 hours

#218 Achievement completion feature and auto-generation on challenge creation
  application/backend/api/management/commands/create_mock_data.py
  application/backend/api/tip/__init__.py
  application/backend/api/waste/__init__.py
  application/backend/api/waste/waste_views.py
  application/backend/challenges/serializers.py
Labels: pr:urgent, 1-3 hours

#228 Integrate Open Trivia DB API for Random Trivia Feature
  application/backend/api/opentdb/__init__.py
  application/backend/api/opentdb/trivia_fetcher.py
  application/backend/api/opentdb/views.py
  application/backend/api/tests/test_opentdb.py
  application/backend/api/urls.py
  application/backend/api/waste/waste_views.py
Labels: pr:high, 1-3 hours

#233 merge feature/display-current-user-in-leaderboard into main
  application/backend/api/tests/test_wastes.py
  application/backend/api/waste/waste_views.py
Labels: enhancement, pr:high, 1-3 hours

#236 merge Feature/achievement endpoint into main
  application/backend/api/achievement/__init__.py
  application/backend/api/achievement/achievement_serializer.py
  application/backend/api/achievement/achievement_views.py
  application/backend/api/tests/test_achievements.py
  application/backend/api/urls.py
Labels: enhancement, pr:high, 1-3 hours

#239 Updated the Leaderboard page with some improvements.
  application/front-end/zero-waste/src/Leaderboard/Leaderboard.jsx
Labels: pr:urgent, 1-3 hours
